pipeline:
  build:
    image: imo/luarocks${LUA}:latest
    commands:
        - luarocks install lua-cjson 2.1.0-1
        - luarocks install lua-requests
        - luarocks install busted
        - busted -o TAP spec/
matrix:
  LUA:
    - 5.1
    - 5.2
    - 5.3